/**
 * Fallback helpers for writing assessment flow.
 * Used when one of AI-powered assessment steps fails.
 */

const IELTS_DEFAULT_CRITERION = 6;

function normalizeLevel(level) {
  return String(level || 'IELTS').toUpperCase();
}

function clampBand(value) {
  const num = Number(value);
  if (!Number.isFinite(num)) {
    return 0;
  }
  return Math.max(0, Math.min(9, Math.round(num * 2) / 2));
}

export function calculateWordCount(text = '') {
  return String(text)
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .length;
}

export function calculateSentenceCount(text = '') {
  const value = String(text).trim();
  if (!value) {
    return 0;
  }

  const matches = value.match(/[.!?]+(?=\s|$)/g);
  return matches ? matches.length : 1;
}

export function isEnglish(text = '') {
  const value = String(text).trim();
  if (!value) {
    return false;
  }

  const latinChars = (value.match(/[A-Za-z]/g) || []).length;
  const totalLetters = (value.match(/[A-Za-z\u0400-\u04FF]/g) || []).length;
  if (totalLetters === 0) {
    return false;
  }

  return latinChars / totalLetters >= 0.6;
}

export function generateMinimalData(answer = '', topic = '') {
  const text = String(answer || '');
  const topicText = String(topic || '');

  return {
    topic: topicText,
    wordCount: calculateWordCount(text),
    sentenceCount: calculateSentenceCount(text),
    paragraphCount: text.split(/\n+/).filter((line) => line.trim()).length || 1,
    detectedLanguage: isEnglish(text) ? 'en' : 'unknown',
    lexicalVariety: null,
    grammarErrorDensity: null,
    notes: 'Generated by fallback helpers'
  };
}

export function generateFallbackCriterionScore(criterion = 'taskResponse', level = 'IELTS') {
  const normalizedLevel = normalizeLevel(level);
  const base = IELTS_DEFAULT_CRITERION;
  const byCriterionOffset = {
    taskResponse: 0,
    coherenceCohesion: 0,
    lexicalResource: 0,
    grammaticalRange: 0
  };

  const value = clampBand(base + (byCriterionOffset[criterion] ?? 0));
  return {
    criterion,
    score: value,
    confidence: 'low',
    source: `fallback-${normalizedLevel.toLowerCase()}`
  };
}

export function validateCriterionScores(scores = {}) {
  const normalized = {};
  const warnings = [];
  const criteria = ['taskResponse', 'coherenceCohesion', 'lexicalResource', 'grammaticalRange'];

  criteria.forEach((key) => {
    const raw = scores[key];
    const value = clampBand(raw);
    normalized[key] = value;

    if (raw !== value) {
      warnings.push(`${key} adjusted from ${raw} to ${value}`);
    }
  });

  return {
    valid: warnings.length === 0,
    scores: normalized,
    warnings
  };
}

export function mergeCriterionScores(primary = {}, fallback = {}) {
  const merged = {};
  const criteria = ['taskResponse', 'coherenceCohesion', 'lexicalResource', 'grammaticalRange'];

  criteria.forEach((key) => {
    const primaryValue = primary[key];
    const fallbackValue = fallback[key];
    const resolved = primaryValue ?? fallbackValue ?? 0;
    merged[key] = clampBand(resolved);
  });

  const overall =
    (merged.taskResponse +
      merged.coherenceCohesion +
      merged.lexicalResource +
      merged.grammaticalRange) / 4;

  return {
    ...merged,
    overall: clampBand(overall)
  };
}

export function generateFallbackFeedback(scores = {}, locale = 'en') {
  const safeLocale = ['en', 'ru', 'uz'].includes(locale) ? locale : 'en';
  const overall = clampBand(
    scores.overall ??
      (Number(scores.taskResponse || 0) +
        Number(scores.coherenceCohesion || 0) +
        Number(scores.lexicalResource || 0) +
        Number(scores.grammaticalRange || 0)) /
        4
  );

  const templates = {
    en: {
      motivationalText: 'Good effort. Keep practicing to improve your writing skills.',
      detailedFeedback:
        'Automated feedback is temporarily limited. Focus on idea development, structure, vocabulary range, and grammar accuracy.',
      recommendation: 'Write regularly and review common grammar and cohesion patterns.'
    },
    ru: {
      motivationalText: 'Хорошая попытка. Продолжайте практиковаться, чтобы улучшить письмо.',
      detailedFeedback:
        'Автоматическая обратная связь временно ограничена. Сфокусируйтесь на раскрытии идеи, структуре, словарном запасе и точности грамматики.',
      recommendation: 'Пишите регулярно и повторяйте типичные грамматические и связующие конструкции.'
    },
    uz: {
      motivationalText: 'Yaxshi urinish. Yozish ko\'nikmalaringizni yaxshilash uchun mashqni davom ettiring.',
      detailedFeedback:
        'Avtomatik fikr-mulohaza hozircha cheklangan. G\'oyani rivojlantirish, tuzilma, lug\'at boyligi va grammatika aniqligiga e\'tibor bering.',
      recommendation: 'Muntazam yozing va grammatika hamda bog\'lovchi vositalarni qayta ko\'rib chiqing.'
    }
  };

  return {
    ...templates[safeLocale],
    overallBand: overall,
    source: 'fallback'
  };
}

export function generateErrorResponse(error, context = {}) {
  const message = error instanceof Error ? error.message : String(error || 'Unknown error');
  return {
    success: false,
    error: {
      message,
      context,
      timestamp: new Date().toISOString()
    }
  };
}
